trigger:
- test/ci-cd

pool:
  vmImage: ubuntu-latest

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '20.19.2'
  displayName: 'Install Node.js'

- script: |
    npm install --global corepack
    corepack enable
    corepack install
  displayName: 'Install and enable corepack'

- script: |
    corepack install
  displayName: 'Install Yarn'

- script: |
    yarn
  displayName: 'Install project dependencies'

- script: |
    EXPO_TOKEN=$(eas-access-token) npx eas-cli build --profile development --platform all --non-interactive
  displayName: 'Build with EAS'
