trigger:
- dev
- main

pool:
  vmImage: ubuntu-latest

variables:
- group: 30005-thm-variable-group
- name: easProfile
  ${{ if eq(variables['Build.SourceBranchName'], 'main') }}:
    value: preview
  ${{ else }}:
    value: development

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '20.19.2'
  displayName: 'Install Node.js'

- script: |
    npm install --global corepack
    corepack enable
    corepack install
  displayName: 'Install and enable corepack'

- script: corepack install
  displayName: 'Install Yarn'

- script: yarn
  displayName: 'Install project dependencies'

- script: EXPO_TOKEN=$(eas-access-token) npx eas-cli build --profile ${{ variables.easProfile }} --platform all --non-interactive --no-wait
  displayName: 'Build (${{ variables.easProfile }}) with EAS'